### ISSUE TITLE
Implement Real-time Face Recognition in main.py

### ISSUE THREAD

**Issue by sanskaromar** [ContriHUB/SecureFace#1]
### Description
In the current project, we have identified the need to implement real-time face recognition functionality in the `main.py` file. This feature would enable the system to perform face recognition on video frames captured from a camera source and display the results in real time.

### Expected behavior
- The real_time_detection function in `main.py` should capture video from a camera source.
- For each frame, the system should perform face recognition using the trained model.
- The recognized faces should be annotated on the frame.
- The user should be able to press 'q' to quit the real-time detection.

### Additional context

- Assume that the code for face recognition and model loading is already implemented in the project.
- Comments indicating the structure and functionality of the real_time_detection function are present in the code.
- Refer to `# TODO 1`  in main.py to locate the function you need to modify.

**Comment by meenakshi3151** [comment]
Sir I would like to contribute to this project . sir can you please assign this to me?

**Comment by sanskaromar** [comment]
Sure, Go ahead @meenakshi3151

**Comment by harmonicfunc** [comment]
sir, can I work on this?

**Comment by sanskaromar** [comment]
@harmonicfunc You need to request it from Contrihub  website as well.

@meenakshi3151 Any progress?

**Comment by meenakshi3151** [comment]
Yes sir I have written the function yesterday currently getting some errors and trying to resolve it .

**Comment by sanskaromar** [comment]
> Yes sir I have written the function yesterday currently getting some errors and trying to resolve it .

Sure! Be mindful of the timer for the issue.
