### ISSUE TITLE
Check the functionality of each system now and check if it's working as expected. (main.py, security_system.py, train_model.py and tests)

### ISSUE THREAD

**Issue by Aqua-16** [ContriHUB/SecureFace#23]
### Description

Conduct a comprehensive review and testing of the system components, including main.py, security_system.py, train_model.py, and the associated test cases. The primary objective is to ensure that each component functions as expected, identify and report any bugs, and suggest possible improvements while performing a thorough code refactoring.

### Expected Behavior

The components are working without any issues and generate expected results.

### Additional Context

Refer to the following comment: https://github.com/ContriHUB/SecureFace/pull/22#issuecomment-1762637226

**Comment by Aqua-16** [comment]
@sanskaromar Made the issue. Will start working on it soon.

**Comment by sanskaromar** [comment]
Hey, follow the issue template. Add a description from that comment here, also. You can use chatgpt for this ig. Not much effort.

Also, Now you can get it assigned from Contrihub.
