### ISSUE TITLE
Implement Logging in Security System

### ISSUE THREAD

**Issue by sanskaromar** [ContriHUB/SecureFace#6]
### Description
In the `security_system.py` file, there are two sections marked with `# TODO 2` that require implementation. These tasks involve configuring logging settings and logging access attempts to the `access_logs.log` file.

### Expected behavior

1. **Logging Configuration (in `__init__` method):**
   - Implement the code within the `# TODO 2` section to configure logging.
   - Logs should be written to the `access_logs.log` file.
   - Set the logging level to INFO.
   - Use the specified log format: `'%(asctime)s - %(message)s'`.

2. **Access Attempt Logging (in `log_access_attempt` method):**
   - Implement the code within the `# TODO 2` section to log access attempts.
   - Access attempt logs should be in the following format:
     `<timestamp> - Person: <person_name>, Authorized: <is_authorized>`.

### Additional context
- The code structure and comments are already provided in the file.
- You can locate the specific sections that need implementation by searching for `# TODO 2` in the `security_system.py` file.

Completing these tasks will ensure that the security system logs access attempts and maintains them in the `access_logs.log` file. Unauthorized access attempts trigger a notification via the `send_firebase_notification` method.

**Comment by Nandika-A** [comment]
Hello @sanskaromar, can I work on this issue?

**Comment by sanskaromar** [comment]
@Nandika-A Sure go ahead!
