### ISSUE TITLE
Implement Real-Time Face Recognition in security_system.py

### ISSUE THREAD

**Issue by sanskaromar** [ContriHUB/SecureFace#7]
### Description
In the `security_system.py` file, there is a section marked with `# TODO 3` that requires implementation. This task involves implementing real-time face recognition within the `recognize_face` method.

### Expected behavior

1. **Face Detection and Recognition (in `recognize_face` method):**
   - Implement the code within the `# TODO 3` section to achieve the following:
     - Convert the input frame to grayscale for face detection.
     - Load the custom Haar Cascade classifier for face detection.
     - Perform face detection on the grayscale frame.
     - Iterate through each detected face.
     - Extract the detected face region.
     - Perform facial recognition on the detected face.
     - Draw a bounding box around the detected face.
     - Annotate the frame with the recognized user's name and authorization status.
     - Log the access attempt (as described in a previous task).
   - Your code should enable real-time face recognition on video frames captured from a camera source.

### Additional context
- The code structure and comments are already provided in the `security_system.py` file.
- You can locate the specific section that needs implementation by searching for `# TODO 3` in the `security_system.py` file.

Completing this task will ensure that the `recognize_face` method performs real-time face recognition and annotates video frames with recognized user information.

**Comment by Aqua-16** [comment]
@sanskaromar Sir I would like to contribute to this if possible.

**Comment by sanskaromar** [comment]
Hey @Aqua-16 , Please work on your previously assigned issue first. Let's get that merged first!

**Comment by sanskaromar** [comment]
You can request it now from Contrihub. @Aqua-16

**Comment by Aqua-16** [comment]
Sir I have tried to improve my commits this time.
