### ISSUE TITLE
Fix Errors in Access Logging and Face Detection Tests

### ISSUE THREAD

**Issue by sanskaromar** [ContriHUB/SecureFace#8]
### Description
The current implementation of the `test_access_logging` and `test_face_detection` tests in the `test_security_system.py` file is producing errors. This task is focused on identifying and resolving these errors to ensure that the tests run successfully.

### Expected behavior

1. **Access Logging Test (in `test_access_logging`):**
   - Review the `test_access_logging` test case.
   - Identify and fix any errors in the test code.
   - Ensure that the test correctly checks if access attempts are logged as expected.
   - Verify that the test file `app/access_logs.log` contains the correct log entry based on the provided `person_name` and `is_authorized` values.

2. **Face Detection Test (in `test_face_detection`):**
   - Review the `test_face_detection` test case.
   - Identify and fix any errors in the test code.
   - Ensure that the test correctly checks if faces are detected in the processed image.
   - Verify that the test provides accurate results for face detection.

### Additional context
- The test cases are part of the `test_security_system.py` file.
- The test setup initializes the `SecuritySystem` object with a test model and cascade classifier.
- The `setUp` method is responsible for setting up the necessary environment for testing.

Fixing these issues will help ensure that the access logging and face detection tests provide accurate results and contribute to the overall reliability of the project.

**Comment by Aqua-16** [comment]
@sanskaromar Sir I wish to work on this but I'm getting an error when I try to submit a request assignment on ContriHUB.
![image](https://github.com/ContriHUB/SecureFace/assets/123102778/2e1a8ab6-838e-49d2-97ae-deb8b124e468)

**Comment by sanskaromar** [comment]
> @sanskaromar Sir I wish to work on this but I'm getting an error when I try to submit a request assignment on ContriHUB. ![image](https://user-images.githubusercontent.com/123102778/273876527-2e1a8ab6-838e-49d2-97ae-deb8b124e468.png)

It is currently assigned to @Nandika-A that's why you can't request it.

**Comment by Aqua-16** [comment]
Ah, since there was no assigned message in here, I didn't think about that.
Thank you for the clarification

**Comment by sanskaromar** [comment]
I can't assign someone here unless they participate in the conversation here. That's why I couldn't assign her here.

**Comment by Nandika-A** [comment]
@sanskaromar The tests are not successful for some code in security_system.py. This is mainly due to improper access to variables and files. So should I correct the code in the security_system file to pass all the test cases, or make changes in the test_security_system.py file? The tests correctly identify the errors.

**Comment by sanskaromar** [comment]
> @sanskaromar The tests are not successful for some code in security_system.py. This is mainly due to improper access to variables and files. So should I correct the code in the security_system file to pass all the test cases, or make changes in the test_security_system.py file? The tests correctly identify the errors.

Which variables and files?

**Comment by Nandika-A** [comment]
> > @sanskaromar The tests are not successful for some code in security_system.py. This is mainly due to improper access to variables and files. So should I correct the code in the security_system file to pass all the test cases, or make changes in the test_security_system.py file? The tests correctly identify the errors.
> 
> Which variables and files?

https://github.com/Nandika-A/SecureFace/commit/2991be6135302dbd1006e2e397d577ce82400f5d
@sanskaromar I have changed them in this commit. Please check if this is correct or should I revert it?
After this, all the tests are running successfully.

**Comment by sanskaromar** [comment]
> > > @sanskaromar The tests are not successful for some code in security_system.py. This is mainly due to improper access to variables and files. So should I correct the code in the security_system file to pass all the test cases, or make changes in the test_security_system.py file? The tests correctly identify the errors.
> > 
> > 
> > Which variables and files?
> 
> [Nandika-A@2991be6](https://github.com/Nandika-A/SecureFace/commit/2991be6135302dbd1006e2e397d577ce82400f5d) @sanskaromar I have changed them in this commit. Please check if this is correct or should I revert it? After this, all the tests are running successfully.

I don't think those changes will make much difference on the tests.

**Comment by Nandika-A** [comment]
> > > > @sanskaromar The tests are not successful for some code in security_system.py. This is mainly due to improper access to variables and files. So should I correct the code in the security_system file to pass all the test cases, or make changes in the test_security_system.py file? The tests correctly identify the errors.
> > > 
> > > 
> > > Which variables and files?
> > 
> > 
> > [Nandika-A@2991be6](https://github.com/Nandika-A/SecureFace/commit/2991be6135302dbd1006e2e397d577ce82400f5d) @sanskaromar I have changed them in this commit. Please check if this is correct or should I revert it? After this, all the tests are running successfully.
> 
> I don't think those changes will make much difference on the tests.

@sanskaromar sir, before this the tests were giving errors for me.
For this issue, do I have to test for different scenarios in the code and make changes for that in test_security_system.py?

**Comment by sanskaromar** [comment]
Yes. You are supposed to improve the tests themselves. Regarding access things, since some PRs are not yet merged for security_system.py, they may give some problems. But your test should be independent of the code. They should test if everything is as expected expected.

**Comment by Nandika-A** [comment]
@sanskaromar can you suggest how can I look for different scenarios for testing?

**Comment by sanskaromar** [comment]
> @sanskaromar can you suggest how can I look for different scenarios for testing?

For now, I'll just accept your changes. We can later work on further improving tests.
