### ISSUE TITLE
Implement Incomplete Test for Facial Recognition

### ISSUE THREAD

**Issue by sanskaromar** [ContriHUB/SecureFace#9]
### Description
The `test_facial_recognition` test case in the `test_security_system.py` file is currently incomplete and needs to be implemented. This task focuses on completing the test to ensure that facial recognition functionality is thoroughly tested.

### Expected behavior

1. **Facial Recognition Test (in `test_facial_recognition`):**
   - Implement the `test_facial_recognition` test case.
   - Ensure that the test case correctly checks the functionality of the `recognize_face` method.
   - Verify that recognized face labels are present in the processed image.
   - Provide thorough testing to validate facial recognition accuracy.

### Additional context
- The test case is part of the `test_security_system.py` file.
- The `setUp` method initializes the `SecuritySystem` object with a test model and cascade classifier.
- The existing test cases in the file check access logging and face detection functionality.

Completing this test will contribute to a comprehensive assessment of the facial recognition feature and help ensure its accuracy and reliability in the project.

**Comment by Aqua-16** [comment]
@sanskaromar Sir the import of `app.security_system` is not able to pull the module for the use of `SecuritySystem` class when I'm using a virtual environment. I even tried adding an __init.py__ file to the app directory but even that didn't seem to work. Any suggestions?

**Comment by sanskaromar** [comment]
You don't need to add any `__init__.py` files. It should work fine. Anyways what errors are you facing? We cant continue this convo over discord dms as well.

**Comment by Aqua-16** [comment]
Alright, I'll DM you the details.
